name: Generate Snake

on:
  schedule: # Runs once a day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Generates the snake animation
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: sohaibzahid197
          outputs: dist/github-contribution-grid-snake.svg

      # Pushes the generated snake to the output branch
      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
